[[edges]]
scope = "Parent"
from = "replace_isToggleEnabled_with_boolean_literal"
to = [
  "something_and_true",
  "true_and_something",
  "not_true",
  "not_false",
  "true_or_something",
  "something_or_true",
]

[[edges]]
scope = "Parent"
from = "else_if_always_true"
to = ["if_always_true"]
